# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Dj Albert Olivé - Mashups, Remixes and Top Trance Mix."
email: "djalbertolive@gmail.com"
description: "Albert Olivé (Pd Oli - La Factoria - Disco Inferno) is a deejay and producer from Barcelona. Listen his remixes, mashups and his radio show Top Trance Mix."
newsDescription: "In this section you will find the latest news of Dj Albert Olivé. Tour dates, new Mashups / Bootlegs, the Top Trance Mix Radio show, and many more."
biographyDescription: "This is Albert Olivé official Biography. In this section you will learn about his life, his styles, where does he played and many more."
scheduleDescription: "Here you will find Albert Olivé upcoming concerts or festivals. Don't miss any of them by tracking it."
mashupsDescription: "This is where you will find all Albert Olivé Mashups / Bootlegs. Listen and download all of them directly from this page."
toptrancemixDescription: "At first, Albert Olivé has his own radio show called Top Trance Mix. This show is over but you can listen whenever you want."
contactDescription: "Want to keep in touch with Dj Albert Olivé, send him a message and he will answer you."
baseurl: ""
url: "http://www.djalbertolive.com"
permalink: "/news/:title"
googleAnalyticsTrackingId: "UA-25355880-1"
googleAnalyticsSiteUrl: "auto"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Video del inici
newestYoutube: 'sKEFyJxoRo4'
newestVimeo: ''

# Organizer Info
organizerName: "Dj Albert Olivé"
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: "djalbertolive@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.djalbertolive.com"

# Head
metaKeywords: "albert olive, rumba, dance, electronic, mashup, bootleg, trance, progressive, Top Trance Mix, reggaeton"
twitterAccount: "@djalbertolive"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/biography/", text: "Biography"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/mashups/", text: "Mashups"}
 - {permalink: "/toptrancemix/", text: "Top Trance Mix"}
 - {permalink: "/contact/", text: "Contact"}
bottomNavigationLinks:
 - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# About Block
aboutTitle: "Dj Albert Olivé"
aboutBlock:
 - {title: "About", image: "about.jpg", text: "Albert Olivé Corbella was born in Barcelona in 1988 and indulged his passion for music from a young age.", link: "biography" }
 - {title: "Mashups", image: "mashup.jpg", text: "Albert Olivé has created great Mashups over this years. Here you can listen all of them.", link: "mashups" }
 - {title: "Top Trance Mix", image: "toptrancemix.jpg", text: "At first, Albert Olivé has his own radio show called Top Trance Mix. This show is over but you can listen whenever you want.", link: "toptrancemix" }

# Statistic Block
statisticTitle: "Most listened"
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "4521", specialCharacter: "plays", info: "Manel vs Tata Golosa", detail: "Al Mar Con Los Micrófonos", link: "/mashup/manel-vs-tata-golosa-al-mar-con-los-microfonos/"}
 - {count: "3861", specialCharacter: "plays", info: "Bongo Botrako Vs Boikot", detail: "Kualkier día sale el sol", link: "/mashup/bongo-botrako-vs-boikot-kualkier-día-sale-el-sol/"}
 - {count: "3223", specialCharacter: "plays", info: "ATB vs Bellini", detail: "Samba de Janeiro at 9pm", link: "/mashup/atb-vs-bellini-samba-de-janeiro-at-9pm/"}
 - {count: "2070", specialCharacter: "plays", info: "Bruno Mars vs Adele", detail: "Set fire to the rain with grenade", link: "/mashup/bruno-mars-vs-adele-set-fire-to-the-rain-with-grenade/"}

# Latest Mashup Block
latestNewsTitle: "Latest Mashups"

# Mashups
mashupTitle: "Latest Mashups"

# Follow me
followMeTitle: "Follow me"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://djalbertolive.us3.list-manage2.com/subscribe?u=66b4fa08073c3baf4dbe43f9c&amp;id=3f1a5a255c"
subscribeInfo: "Subscribe to Albert Olivé newsletter to be the first to listen his newest mashups"

# Footer
socialLinks:
 - {link: "https://facebook.com/albertoliveDj", icon: "facebook"}
 - {link: "https://twitter.com/intent/user?screen_name=djalbertolive", icon: "twitter"}
 - {link: "https://plus.google.com/u/0/+Djalbertolive", icon: "google-plus"}
 - {permalink: "/feed.xml", icon: "rss"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "djalbertolive"

# Speakers List Block
showSessions: true

